Implement shared credentials across gridscale tools (#136)
gridscale/gscloud pull request #153
Opened 2022-06-08 09:35 UTC by JanLukasGithub

Changes the config path from `/gscloud/config.yaml` to `/gridscale/config.yaml` as proposed in #136 

Should I implement a tool to copy the old config to the new location if the old but not the new one is present, or something along those lines?

2022-06-08 10:05 UTC, nvthongswansea commented
@JanLukasGithub this is gonna be a breaking change.

2022-06-08 10:13 UTC, JanLukasGithub commented
> @JanLukasGithub this is gonna be a breaking change.

That's why I asked

> Should I implement a tool to copy the old config to the new location, if the old but not the new one is present, or something along those lines?

And yes this should only be pulled for the next major release (The issue has milestone v0.12.0)

2022-06-08 10:15 UTC, JanLukasGithub commented on runtime/config.go
> +	Accounts []AccountEntry `yaml:"projects"`
imo "projects" is just a bad name as this makes the code less readable, but consistency is king...

2022-06-08 11:14 UTC, nvthongswansea commented
> > @JanLukasGithub this is gonna be a breaking change.
> 
> That's why I asked
> 
> > Should I implement a tool to copy the old config to the new location, if the old but not the new one is present, or something along those lines?
> 
> And yes this should only be pulled for the next major release (The issue has milestone v0.12.0)

Yep, a migration will be needed for the new config.

2022-06-15 16:54 UTC, bkircher requested changes
Looks OK from my side. Wouldn't bother much with automatically moving the old config to the new gridscale/config.yaml path, but it's fine. What is missing is a good Changelog entry. So that users can immediately see the change and act accordingly. Updating the binary is an active step anyway.

2022-06-15 16:54 UTC, bkircher commented on README.md
>          - "$HOME/.config/gscloud/config.yaml"
Should be changed

2022-06-17 07:31 UTC, JanLukasGithub commented
Should I put the changelog as v0.11.1 or as v0.12.0? I think v0.12.0 is more adequate for the amount and impact of the changes

2022-06-17 07:46 UTC, bkircher commented
@JanLukasGithub Agree, v0.12.0 makes more sense.

2022-06-17 07:52 UTC, bkircher commented
Looks great! Everything looks ready from my side

2022-06-17 08:14 UTC, JanLukasGithub commented
Rebased

2022-06-30 06:44 UTC, bkircher commented
Picked into master branch

2022-06-30 06:44 UTC, closed without merging